services:
  progvoraz-console:
    build:
      context: .
      dockerfile: Dockerfile
    image: progvoraz:latest
    pull_policy: build
    volumes:
      - ./monedas.txt:/app/monedas.txt:ro
      - ./stock.txt:/app/stock.txt
      - ./historial.txt:/app/historial.txt
      - ./reporte_global.txt:/app/reporte_global.txt
    stdin_open: true
    tty: true
    command: [ "console" ]

  progvoraz-gui-portable:
    build:
      context: .
      dockerfile: Dockerfile
    image: progvoraz:latest
    pull_policy: build
    volumes:
      - ./monedas.txt:/app/monedas.txt:ro
      - ./stock.txt:/app/stock.txt
      - ./historial.txt:/app/historial.txt
      - ./reporte_global.txt:/app/reporte_global.txt
    stdin_open: true
    tty: true
    command: [ "gui" ]

  progvoraz-test:
    build:
      context: .
      dockerfile: Dockerfile
    image: progvoraz:latest
    pull_policy: build
    volumes:
      - ./monedas.txt:/app/monedas.txt:ro
      - ./stock.txt:/app/stock.txt
      - ./historial.txt:/app/historial.txt
      - ./reporte_global.txt:/app/reporte_global.txt
    command: [ "test" ]
